[colors]

bg = #0D1A35FF
#bg-alt = #030818
bg-alt = #090F23
fg = #acb0d0
fg-alt = #0B1428


#bg = #16161e
#bg-alt = #20212C
#fg-alt = #0D1A35
#fg-alt=#F5D5E72

red = #ff7a93

trans = #00000000
semi-trans-black = #cc000000

shade-1 = #32344a
shade-2 = #444b6a
shade-3 = #787c99
shade-4 = #CACACE
shade-5 = #acb0d0

[bar/main]
width = 100%
height = 30
offset-y = 0
top = true
fixed-center = true

override-redirect = false

scroll-up = next
scroll-down = prev

#wm-restack = bspwm

enable-ipc = true

background = ${colors.bg}
foreground = ${colors.fg}

font-0 = fixed:pixelsize=12;1
font-1 = unifont:fontformat=truetype:size=8:antialias=false;0
font-2 = siji:pixelsize=10;1
font-3 = Font Awesome 5 Free:pixelsize=12;2
font-4 = Font Awesome 5 Free Solid:pixelsize=12;2
font-5 = Font Awesome 5 Brands:pixelsize=12;2

# ICON SIZE: CHANGE SIZE=XX
font-6 = "JetBrains Mono Nerd Font:style=Medium:size=12;2"
font-7 = "JetBrains Mono Nerd Font:style=Bold:size=10;2"
font-8 = "JetBrainsMono Nerd Font:size=19;5"
font-9 = "Material Icons Outlined:9;4"
font-10 = "Material Icons Round:9;4"
font-11 = "Source Han Sans CN:size=9;2"

#modules-left = bspwm 
modules-left = i3
modules-center = xwindow 
modules-right = wlan pulseaudio memory cpu cpu-temp battery margin date 

cursor-click = pointer

[module/bspwm]
type = internal/bspwm
pin-workspaces = true

format = <label-state> <label-mode>

label-focused = %index%
label-focused-foreground = ${colors.shade-5}
label-focused-padding = 2

label-occupied = %index%
label-occupied-foreground = ${colors.shade-3}
label-occupied-padding = 2

label-empty = %index%
label-empty-foreground = ${colors.shade-1}
label-empty-padding = 2

[bar/external]
monitor = DP1-1 
modules-right = battery date
inherit = bar/main

[settings]
screenchange-reload = true

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM: "
format-padding=2
format-prefix-foreground = ${colors.fg}
#label = %percentage_used%% (%gb_used% / %gb_free%)
label = %percentage_used%%

[module/cpu]
type = internal/cpu
interval = 2
format = <label>
format-padding=1
#format = <label> <ramp-coreload>
format-prefix-foreground = ${colors.fg}
label = CPU: %percentage:2%%
#ramp-coreload-0 = ▁
#ramp-coreload-1 = ▂
#ramp-coreload-2 = ▃
#ramp-coreload-3 = ▄
#ramp-coreload-4 = ▅
#ramp-coreload-5 = ▆
#ramp-coreload-6 = ▇
#ramp-coreload-7 = █

[module/cpu-temp]
type = custom/script
exec = ~/scripts/temp
format-prefix= " "
format-padding=2
interval = 5

[module/xbacklight]
type = internal/xbacklight

format = <label> <bar>
label = BL

bar-width = 10
bar-indicator = |
bar-indicator-foreground = #fff
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = #9f78e1
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

[module/battery]
type = internal/battery
battery = BAT0
adapter = ADP1
full-at = 98
format-charging =  <label-charging>
label-charging = %percentage:2%%
format-charging-padding = 2
format-charging-foreground = ${colors.fg}
format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%
format-discharging-foreground = ${colors.fg}
format-full-prefix = "  "
ramp-capacity-0 = "  "
ramp-capacity-1 = "  "
ramp-capacity-2 = "  "
ramp-capacity-3 = "  "
ramp-capacity-4 = "  "
ramp-capacity-0-foreground = ${colors.red}
animation-charging-framerate = 910
format-discharging-padding = 1


[module/i3]
type = internal/i3
format = <label-state> <label-mode>
index-sort = true
wrapping-scroll = false

; Only show workspaces on the same output as the bar
;pin-workspaces = true

label-mode-padding = 2
label-mode-foreground = #fff
label-mode-background = ${colors.bg}

; focused = Active workspace on focused monitor
label-focused = %index% 
label-focused-background = ${colors.bg-alt}
label-focused-padding = 2

; unfocused = Inactive workspace on any monitor
label-unfocused = %index% 
label-unfocused-padding = 2

; visible = Active workspace on unfocused monitor
#label-visible = %index%
#label-visible-background = ${self.label-focused-background}
#label-visible-underline = ${self.label-focused-underline}
#label-visible-padding = ${self.label-focused-padding}

; urgent = Workspace with urgency hint set
label-urgent = %index%
label-urgent-background = ${colors.red}
label-urgent-padding = 2

; Separator in between workspaces
; label-separator = |



[module/date]
type = internal/date
interval = 1

time ="%H:%M"
time-alt = "%a, %b %d %H:%M"

format = <label>
format-foreground = ${colors.fg}
format-padding = 1
format-prefix = %{T5} %{T-}
label = %{T1}%time%%{T-}
label-padding = 1

[module/margin]
type = custom/text

content = %{T2} %{T-}
#content = %{T2}%{T-}
content-foreground = ${colors.trans}

[module/pulseaudio]
type = internal/pulseaudio
use-ui-max = false

format-volume = <label-volume>
format-volume-padding = 1
format-volume-prefix = %{T4}%{T-}
#format-volume-prefix = %{T4}%{T-}
format-volume-prefix-foreground = ${colors.fg}
label-volume = %{T1}  %percentage%%%{T-}
label-volume-foreground = ${colors.fg}
label-volume-padding = 1

format-muted = <label-muted>
format-muted-padding = 2
#format-muted-prefix = 
format-muted-prefix-foreground = ${colors.fg-alt}
label-muted = %{T1}  %percentage%%%{T-}
label-muted-foreground = ${colors.fg}
label-muted-pdding = 1

click-right = pavucontrol &


[module/wlan]
type = internal/network
#interface = wlan0
interface = wlp0s20f3 
interval = 5.0
# hvorfor funker det ikke?
click-left = nm-applet&

format-connected = <label-connected>
format-connected-padding = 1
label-connected = %{A1:wifimenu:}   %essid%%{A}
label-connected-foreground = ${colors.fg}
label-connected-padding = 1

format-disconnected = <label-disconnected>
format-disconnected-padding = 1
label-disconnected = %{A1:wifimenu:}   %{A}
label-disconnected-foreground = ${colors.shade-1}
label-disconnected-padding = 1a
